apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: forexratenegotiationacl
  name: forexratenegotiationacl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forexratenegotiationacl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: forexratenegotiationacl
    spec:
      containers:
        - image: harbor.fstop.com.tw/xp/forex-rate-negotiation-acl:${VERSION}
          name: forex-rate-negotiation-acl
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: forexratenegotiationacl
  name: forexratenegotiationacl-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: forexratenegotiationacl
  type: LoadBalancer
status:
  loadBalancer: {}